[project]
name = "rectoform-sspu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyofd==0.5.1",
    "lxml==5.3.1",
    "openai>=2.6.1",
    "openpyxl==3.1.5",
    "pdfplumber==0.11.6",
    "requests==2.32.3",
]
